# Generated by Django 4.2.7 on 2023-11-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrequest', '0002_alter_category_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(upload_to='vrequest/static/category'),
        ),
    ]
