# Generated by Django 4.2.7 on 2023-11-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrequest', '0004_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowAllFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('foodImage', models.ImageField(upload_to='vrequest/static/allFoodImg')),
                ('description', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('slug', models.SlugField(default='')),
            ],
        ),
    ]
